apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foo
  name: foo-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: foo
        tier: backend
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: info
        - name: REDIS_URI
          valueFrom:
            secretKeyRef:
              key: uri
              name: redis
        image: gcr.io/my-project/foo-service:3adfa3e
        name: foo-web
        ports:
        - containerPort: 3001
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
